# Generated by Django 4.0.3 on 2022-03-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stop_delete_transportstop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': 'Direction', 'verbose_name_plural': 'Directions'},
        ),
        migrations.AlterModelOptions(
            name='stop',
            options={'verbose_name': 'Stop', 'verbose_name_plural': 'Stops'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': 'Transport', 'verbose_name_plural': 'Transports'},
        ),
    ]
