# Generated by Django 4.0.3 on 2022-03-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_city_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
