# Generated by Django 4.0.3 on 2022-04-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transport_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
