# Generated by Django 4.0.3 on 2022-05-02 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transport_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='transport',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_zones', to='core.country')),
            ],
            options={
                'verbose_name': 'Time Zone',
                'verbose_name_plural': 'Time Zones',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='time_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_zones', to='core.timezone'),
        ),
    ]
