# Generated by Django 4.0.3 on 2022-05-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_city_country_remove_transport_timezone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='update_date',
        ),
        migrations.AddField(
            model_name='stop',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
