# Generated by Django 4.0.3 on 2022-05-03 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_transport_update_date_stop_update_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yandex_id', models.CharField(max_length=100)),
                ('time_format', models.CharField(choices=[('time_interval', 'Time interval'), ('time', 'Time')], default='time_interval', max_length=13)),
                ('main_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.stop')),
            ],
        ),
    ]
