# Generated by Django 4.0.3 on 2022-05-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='yandex_id',
            new_name='user_id',
        ),
    ]
