# Generated by Django 4.0.3 on 2022-05-15 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_user_user_id_user_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='time_format',
        ),
    ]
