# Generated by Django 4.0.3 on 2022-05-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_user_time_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
